#This is a yaml formatted file
#declared variables to be passed into your templates.

deploymentName: accounts-deployment
serviceName: accounts
appLabel: accounts
appName: accounts

replicaCount: 1

image:
  repository: usnamemonu/accounts
  tag: v1
  
containerPort: 8113

service:
  type: LoadBalancer         #expose to client thats why using LoadBalancer instead ClusterIP
  port: 8113
  targetPort: 8113
  
appname_enabled: true
profile-enabled: true
config_enabled: true
eureka_enabled: true
resourceserver_enabled: true
otel_enabled: true
kafka_enabled: false
